# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import bittorrent_pb2 as bittorrent__pb2


class BitTorrentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestFileMetadata = channel.unary_unary(
                '/bittorrent.BitTorrent/RequestFileMetadata',
                request_serializer=bittorrent__pb2.Empty.SerializeToString,
                response_deserializer=bittorrent__pb2.FileMetadata.FromString,
                )
        self.RequestFileChunk = channel.unary_unary(
                '/bittorrent.BitTorrent/RequestFileChunk',
                request_serializer=bittorrent__pb2.FileChunkRequest.SerializeToString,
                response_deserializer=bittorrent__pb2.FileChunk.FromString,
                )
        self.UploadFileChunk = channel.unary_unary(
                '/bittorrent.BitTorrent/UploadFileChunk',
                request_serializer=bittorrent__pb2.FileChunk.SerializeToString,
                response_deserializer=bittorrent__pb2.Empty.FromString,
                )


class BitTorrentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestFileMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestFileChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFileChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BitTorrentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestFileMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestFileMetadata,
                    request_deserializer=bittorrent__pb2.Empty.FromString,
                    response_serializer=bittorrent__pb2.FileMetadata.SerializeToString,
            ),
            'RequestFileChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestFileChunk,
                    request_deserializer=bittorrent__pb2.FileChunkRequest.FromString,
                    response_serializer=bittorrent__pb2.FileChunk.SerializeToString,
            ),
            'UploadFileChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFileChunk,
                    request_deserializer=bittorrent__pb2.FileChunk.FromString,
                    response_serializer=bittorrent__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bittorrent.BitTorrent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BitTorrent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestFileMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bittorrent.BitTorrent/RequestFileMetadata',
            bittorrent__pb2.Empty.SerializeToString,
            bittorrent__pb2.FileMetadata.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RequestFileChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bittorrent.BitTorrent/RequestFileChunk',
            bittorrent__pb2.FileChunkRequest.SerializeToString,
            bittorrent__pb2.FileChunk.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadFileChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bittorrent.BitTorrent/UploadFileChunk',
            bittorrent__pb2.FileChunk.SerializeToString,
            bittorrent__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
