# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bittorrent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62ittorrent.proto\x12\nbittorrent\"(\n\tFileChunk\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\".\n\x0c\x46ileMetadata\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty\"!\n\x10\x46ileChunkRequest\x12\r\n\x05index\x18\x01 \x01(\x05\x32\xd6\x01\n\nBitTorrent\x12\x42\n\x13RequestFileMetadata\x12\x11.bittorrent.Empty\x1a\x18.bittorrent.FileMetadata\x12G\n\x10RequestFileChunk\x12\x1c.bittorrent.FileChunkRequest\x1a\x15.bittorrent.FileChunk\x12;\n\x0fUploadFileChunk\x12\x15.bittorrent.FileChunk\x1a\x11.bittorrent.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bittorrent_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILECHUNK']._serialized_start=32
  _globals['_FILECHUNK']._serialized_end=72
  _globals['_FILEMETADATA']._serialized_start=74
  _globals['_FILEMETADATA']._serialized_end=120
  _globals['_EMPTY']._serialized_start=122
  _globals['_EMPTY']._serialized_end=129
  _globals['_FILECHUNKREQUEST']._serialized_start=131
  _globals['_FILECHUNKREQUEST']._serialized_end=164
  _globals['_BITTORRENT']._serialized_start=167
  _globals['_BITTORRENT']._serialized_end=381
# @@protoc_insertion_point(module_scope)
